In [13]:
import pandas as pd
df = pd.read_csv('D:\\Data science\\weather12.csv')
df.fillna('-',inplace=True)
g = df.groupby('name')
for name, name_k in g:
    print(name)
    print(name_k)

Battle at the Mummer's Ford
                          name  year  battle_number             attacker_king  \
1  Battle at the Mummer's Ford   298              2  Joffrey/Tommen Baratheon

  defender_king attacker_1 attacker_2 attacker_3 attacker_4 defender_1  \
1    Robb Stark  Lannister          -          -          -  Baratheon

  defender_2 defender_3 defender_4 attacker_outcome battle_type  major_death  \
1          -          -          -              win      ambush            1

   major_capture attacker_size defender_size
1              0             -           120
Battle of Castle Black
                      name  year  battle_number      attacker_king  \
27  Battle of Castle Black   300             28  Stannis Baratheon

   defender_king attacker_1 attacker_2 attacker_3 attacker_4     defender_1  \
27  Mance Rayder  Free folk     Thenns     Giants          -  Night's Watch

   defender_2 defender_3 defender_4 attacker_outcome battle_type  major_death  \
27  Baratheon          -          -             loss       siege            1

    major_capture attacker_size defender_size
27              1        100000          1240
Battle of Deepwood Motte
                       name  year  battle_number        attacker_king  \
8  Battle of Deepwood Motte   299              9  Balon/Euron Greyjoy

  defender_king attacker_1 attacker_2 attacker_3 attacker_4 defender_1  \
8    Robb Stark    Greyjoy          -          -          -      Stark

  defender_2 defender_3 defender_4 attacker_outcome battle_type  major_death  \
8          -          -          -              win       siege            0

   major_capture attacker_size defender_size
8              0          1000             -
Battle of Duskendale
                    name  year  battle_number attacker_king  \
21  Battle of Duskendale   299             22    Robb Stark

               defender_king attacker_1 attacker_2 attacker_3 attacker_4  \
21  Joffrey/Tommen Baratheon      Stark          -          -          -

   defender_1 defender_2 defender_3 defender_4 attacker_outcome  \
21  Lannister          -          -          -             loss

       battle_type  major_death  major_capture attacker_size defender_size
21  pitched battle            1              0          3000             -
Battle of Moat Cailin
                    name  year  battle_number        attacker_king  \
7  Battle of Moat Cailin   299              8  Balon/Euron Greyjoy

  defender_king attacker_1 attacker_2 attacker_3 attacker_4 defender_1  \
7    Robb Stark    Greyjoy          -          -          -      Stark

  defender_2 defender_3 defender_4 attacker_outcome     battle_type  \
7          -          -          -              win  pitched battle

   major_death  major_capture attacker_size defender_size
7            0              0             -             -
Battle of Oxcross
                 name  year  battle_number attacker_king  \
14  Battle of Oxcross   299             15    Robb Stark

               defender_king attacker_1 attacker_2 attacker_3 attacker_4  \
14  Joffrey/Tommen Baratheon      Stark      Tully          -          -

   defender_1 defender_2 defender_3 defender_4 attacker_outcome battle_type  \
14  Lannister          -          -          -              win      ambush

    major_death  major_capture attacker_size defender_size
14            1              1          6000         10000
Battle of Riverrun
                 name  year  battle_number             attacker_king  \
2  Battle of Riverrun   298              3  Joffrey/Tommen Baratheon

  defender_king attacker_1 attacker_2 attacker_3 attacker_4 defender_1  \
2    Robb Stark  Lannister          -          -          -      Tully

  defender_2 defender_3 defender_4 attacker_outcome     battle_type  \
2          -          -          -              win  pitched battle

   major_death  major_capture attacker_size defender_size
2            0              1         15000         10000
Battle of Torrhen's Square
                          name  year  battle_number attacker_king  \
10  Battle of Torrhen's Square   299             11    Robb Stark

          defender_king attacker_1 attacker_2 attacker_3 attacker_4  \
10  Balon/Euron Greyjoy      Stark          -          -          -

   defender_1 defender_2 defender_3 defender_4 attacker_outcome  \
10    Greyjoy          -          -          -              win

       battle_type  major_death  major_capture attacker_size defender_size
10  pitched battle            0              0           244           900
Battle of Winterfell
                    name  year  battle_number        attacker_king  \
11  Battle of Winterfell   299             12  Balon/Euron Greyjoy

   defender_king attacker_1 attacker_2 attacker_3 attacker_4 defender_1  \
11    Robb Stark    Greyjoy          -          -          -      Stark

   defender_2 defender_3 defender_4 attacker_outcome battle_type  major_death  \
11          -          -          -              win      ambush            0

    major_capture attacker_size defender_size
11              1            20             -
Battle of the Blackwater
                        name  year  battle_number      attacker_king  \
19  Battle of the Blackwater   299             20  Stannis Baratheon

               defender_king attacker_1 attacker_2 attacker_3 attacker_4  \
19  Joffrey/Tommen Baratheon  Baratheon          -          -          -

   defender_1 defender_2 defender_3 defender_4 attacker_outcome  \
19  Lannister          -          -          -             loss

       battle_type  major_death  major_capture attacker_size defender_size
19  pitched battle            1              1         21000          7250
Battle of the Burning Septry
                            name  year  battle_number attacker_king  \
22  Battle of the Burning Septry   299             23             -

   defender_king                   attacker_1 attacker_2 attacker_3  \
22             -  Brotherhood without Banners          -          -

   attacker_4        defender_1 defender_2 defender_3 defender_4  \
22          -  Brave Companions          -          -          -

   attacker_outcome     battle_type  major_death  major_capture attacker_size  \
22              win  pitched battle            0              0             -

   defender_size
22             -
Battle of the Camps
                  name  year  battle_number attacker_king  \
5  Battle of the Camps   298              6    Robb Stark

              defender_king attacker_1 attacker_2 attacker_3 attacker_4  \
5  Joffrey/Tommen Baratheon      Stark      Tully          -          -

  defender_1 defender_2 defender_3 defender_4 attacker_outcome battle_type  \
5  Lannister          -          -          -              win      ambush

   major_death  major_capture attacker_size defender_size
5            0              0          6000         12625
Battle of the Crag
                  name  year  battle_number attacker_king  \
18  Battle of the Crag   299             19    Robb Stark

               defender_king attacker_1 attacker_2 attacker_3 attacker_4  \
18  Joffrey/Tommen Baratheon      Stark          -          -          -

   defender_1 defender_2 defender_3 defender_4 attacker_outcome battle_type  \
18  Lannister          -          -          -              win      ambush

    major_death  major_capture attacker_size defender_size
18            0              0          6000             -
Battle of the Fords
                   name  year  battle_number             attacker_king  \
16  Battle of the Fords   299             17  Joffrey/Tommen Baratheon

   defender_king attacker_1 attacker_2 attacker_3 attacker_4 defender_1  \
16    Robb Stark  Lannister          -          -          -      Tully

   defender_2 defender_3 defender_4 attacker_outcome     battle_type  \
16          -          -          -             loss  pitched battle

    major_death  major_capture attacker_size defender_size
16            0              0         20000         10000
Battle of the Golden Tooth
                         name  year  battle_number             attacker_king  \
0  Battle of the Golden Tooth   298              1  Joffrey/Tommen Baratheon

  defender_king attacker_1 attacker_2 attacker_3 attacker_4 defender_1  \
0    Robb Stark  Lannister          -          -          -      Tully

  defender_2 defender_3 defender_4 attacker_outcome     battle_type  \
0          -          -          -              win  pitched battle

   major_death  major_capture attacker_size defender_size

0            1              0         15000          4000
Battle of the Green Fork
                       name  year  battle_number attacker_king  \
3  Battle of the Green Fork   298              4    Robb Stark

              defender_king attacker_1 attacker_2 attacker_3 attacker_4  \
3  Joffrey/Tommen Baratheon      Stark          -          -          -

  defender_1 defender_2 defender_3 defender_4 attacker_outcome  \
3  Lannister          -          -          -             loss

      battle_type  major_death  major_capture attacker_size defender_size
3  pitched battle            1              1         18000         20000
Battle of the Ruby Ford
                       name  year  battle_number             attacker_king  \
23  Battle of the Ruby Ford   299             24  Joffrey/Tommen Baratheon

   defender_king attacker_1 attacker_2 attacker_3 attacker_4 defender_1  \
23    Robb Stark  Lannister          -          -          -      Stark

   defender_2 defender_3 defender_4 attacker_outcome     battle_type  \
23          -          -          -              win  pitched battle

    major_death  major_capture attacker_size defender_size
23            0              0             -          6000
Battle of the Stony Shore
                        name  year  battle_number        attacker_king  \
9  Battle of the Stony Shore   299             10  Balon/Euron Greyjoy

  defender_king attacker_1 attacker_2 attacker_3 attacker_4 defender_1  \
9    Robb Stark    Greyjoy          -          -          -      Stark

  defender_2 defender_3 defender_4 attacker_outcome battle_type  major_death  \
9          -          -          -              win      ambush            0

   major_capture attacker_size defender_size
9              0           264             -
Battle of the Whispering Wood
                            name  year  battle_number attacker_king  \
4  Battle of the Whispering Wood   298              5    Robb Stark

              defender_king attacker_1 attacker_2 attacker_3 attacker_4  \
4  Joffrey/Tommen Baratheon      Stark      Tully          -          -

  defender_1 defender_2 defender_3 defender_4 attacker_outcome battle_type  \
4  Lannister          -          -          -              win      ambush

   major_death  major_capture attacker_size defender_size
4            1              1          1875          6000
Fall of Moat Cailin
                   name  year  battle_number             attacker_king  \
28  Fall of Moat Cailin   300             29  Joffrey/Tommen Baratheon

          defender_king attacker_1 attacker_2 attacker_3 attacker_4  \
28  Balon/Euron Greyjoy     Bolton          -          -          -

   defender_1 defender_2 defender_3 defender_4 attacker_outcome battle_type  \
28    Greyjoy          -          -          -              win       siege

    major_death  major_capture attacker_size defender_size
28            0              0             -             -
Retaking of Harrenhal
                     name  year  battle_number             attacker_king  \
24  Retaking of Harrenhal   299             25  Joffrey/Tommen Baratheon

   defender_king attacker_1 attacker_2 attacker_3 attacker_4  \
24             -  Lannister          -          -          -

          defender_1 defender_2 defender_3 defender_4 attacker_outcome  \
24  Brave Companions          -          -          -              win

       battle_type  major_death  major_capture attacker_size defender_size
24  pitched battle            1              0             -             -
Sack of Darry
            name  year  battle_number             attacker_king defender_king  \
6  Sack of Darry   298              7  Joffrey/Tommen Baratheon    Robb Stark

  attacker_1 attacker_2 attacker_3 attacker_4 defender_1 defender_2  \
6  Lannister          -          -          -      Darry          -

  defender_3 defender_4 attacker_outcome     battle_type  major_death  \
6          -          -              win  pitched battle            0

   major_capture attacker_size defender_size
6              0             -             -
Sack of Harrenhal
                 name  year  battle_number attacker_king  \
17  Sack of Harrenhal   299             18    Robb Stark

               defender_king attacker_1 attacker_2 attacker_3 attacker_4  \
17  Joffrey/Tommen Baratheon      Stark          -          -          -

   defender_1 defender_2 defender_3 defender_4 attacker_outcome battle_type  \
17  Lannister          -          -          -              win      ambush

    major_death  major_capture attacker_size defender_size
17            1              0           100           100
Sack of Torrhen's Square
                        name  year  battle_number        attacker_king  \
12  Sack of Torrhen's Square   299             13  Balon/Euron Greyjoy

          defender_king attacker_1 attacker_2 attacker_3 attacker_4  \
12  Balon/Euron Greyjoy    Greyjoy          -          -          -

   defender_1 defender_2 defender_3 defender_4 attacker_outcome battle_type  \
12      Stark          -          -          -              win       siege

    major_death  major_capture attacker_size defender_size
12            0              1             -             -
Sack of Winterfell
                  name  year  battle_number             attacker_king  \
13  Sack of Winterfell   299             14  Joffrey/Tommen Baratheon

   defender_king attacker_1 attacker_2 attacker_3 attacker_4 defender_1  \
13    Robb Stark     Bolton    Greyjoy          -          -      Stark

   defender_2 defender_3 defender_4 attacker_outcome battle_type  major_death  \
13          -          -          -              win      ambush            1

    major_capture attacker_size defender_size
13              0           618          2000
Siege of Darry
              name  year  battle_number attacker_king  \
20  Siege of Darry   299             21    Robb Stark

               defender_king attacker_1 attacker_2 attacker_3 attacker_4  \
20  Joffrey/Tommen Baratheon      Darry          -          -          -

   defender_1 defender_2 defender_3 defender_4 attacker_outcome battle_type  \
20  Lannister          -          -          -              win       siege

    major_death  major_capture attacker_size defender_size
20            0              0             -             -
Siege of Seagard
                name  year  battle_number attacker_king  \
26  Siege of Seagard   299             27    Robb Stark

               defender_king attacker_1 attacker_2 attacker_3 attacker_4  \
26  Joffrey/Tommen Baratheon       Frey          -          -          -

   defender_1 defender_2 defender_3 defender_4 attacker_outcome battle_type  \
26  Mallister          -          -          -              win       siege

    major_death  major_capture attacker_size defender_size
26            0              1             -             -
Siege of Storm's End
                    name  year  battle_number      attacker_king  \
15  Siege of Storm's End   299             16  Stannis Baratheon

      defender_king attacker_1 attacker_2 attacker_3 attacker_4 defender_1  \
15  Renly Baratheon  Baratheon          -          -          -  Baratheon

   defender_2 defender_3 defender_4 attacker_outcome battle_type  major_death  \
15          -          -          -              win       siege            1

    major_capture attacker_size defender_size
15              0          5000         20000
The Red Wedding
               name  year  battle_number             attacker_king  \
25  The Red Wedding   299             26  Joffrey/Tommen Baratheon

   defender_king attacker_1 attacker_2 attacker_3 attacker_4 defender_1  \
25    Robb Stark       Frey     Bolton          -          -      Stark

   defender_2 defender_3 defender_4 attacker_outcome battle_type  major_death  \
25          -          -          -              win      ambush            1

    major_capture attacker_size defender_size
25              1          3500          3500

In [15]:
g.describe()

                               year                                         \
                              count   mean std    min    25%    50%    75%
name
Battle at the Mummer's Ford     1.0  298.0 NaN  298.0  298.0  298.0  298.0
Battle of Castle Black          1.0  300.0 NaN  300.0  300.0  300.0  300.0
Battle of Deepwood Motte        1.0  299.0 NaN  299.0  299.0  299.0  299.0
Battle of Duskendale            1.0  299.0 NaN  299.0  299.0  299.0  299.0
Battle of Moat Cailin           1.0  299.0 NaN  299.0  299.0  299.0  299.0
Battle of Oxcross               1.0  299.0 NaN  299.0  299.0  299.0  299.0
Battle of Riverrun              1.0  298.0 NaN  298.0  298.0  298.0  298.0
Battle of Torrhen's Square      1.0  299.0 NaN  299.0  299.0  299.0  299.0
Battle of Winterfell            1.0  299.0 NaN  299.0  299.0  299.0  299.0
Battle of the Blackwater        1.0  299.0 NaN  299.0  299.0  299.0  299.0
Battle of the Burning Septry    1.0  299.0 NaN  299.0  299.0  299.0  299.0
Battle of the Camps             1.0  298.0 NaN  298.0  298.0  298.0  298.0
Battle of the Crag              1.0  299.0 NaN  299.0  299.0  299.0  299.0
Battle of the Fords             1.0  299.0 NaN  299.0  299.0  299.0  299.0
Battle of the Golden Tooth      1.0  298.0 NaN  298.0  298.0  298.0  298.0
Battle of the Green Fork        1.0  298.0 NaN  298.0  298.0  298.0  298.0
Battle of the Ruby Ford         1.0  299.0 NaN  299.0  299.0  299.0  299.0
Battle of the Stony Shore       1.0  299.0 NaN  299.0  299.0  299.0  299.0
Battle of the Whispering Wood   1.0  298.0 NaN  298.0  298.0  298.0  298.0
Fall of Moat Cailin             1.0  300.0 NaN  300.0  300.0  300.0  300.0
Retaking of Harrenhal           1.0  299.0 NaN  299.0  299.0  299.0  299.0
Sack of Darry                   1.0  298.0 NaN  298.0  298.0  298.0  298.0
Sack of Harrenhal               1.0  299.0 NaN  299.0  299.0  299.0  299.0
Sack of Torrhen's Square        1.0  299.0 NaN  299.0  299.0  299.0  299.0
Sack of Winterfell              1.0  299.0 NaN  299.0  299.0  299.0  299.0
Siege of Darry                  1.0  299.0 NaN  299.0  299.0  299.0  299.0
Siege of Seagard                1.0  299.0 NaN  299.0  299.0  299.0  299.0
Siege of Storm's End            1.0  299.0 NaN  299.0  299.0  299.0  299.0
The Red Wedding                 1.0  299.0 NaN  299.0  299.0  299.0  299.0

                                     battle_number        ... major_death  \
                                 max         count  mean  ...         75%
name                                                      ...
Battle at the Mummer's Ford    298.0           1.0   2.0  ...         1.0
Battle of Castle Black         300.0           1.0  28.0  ...         1.0
Battle of Deepwood Motte       299.0           1.0   9.0  ...         0.0
Battle of Duskendale           299.0           1.0  22.0  ...         1.0
Battle of Moat Cailin          299.0           1.0   8.0  ...         0.0
Battle of Oxcross              299.0           1.0  15.0  ...         1.0
Battle of Riverrun             298.0           1.0   3.0  ...         0.0
Battle of Torrhen's Square     299.0           1.0  11.0  ...         0.0
Battle of Winterfell           299.0           1.0  12.0  ...         0.0
Battle of the Blackwater       299.0           1.0  20.0  ...         1.0
Battle of the Burning Septry   299.0           1.0  23.0  ...         0.0
Battle of the Camps            298.0           1.0   6.0  ...         0.0
Battle of the Crag             299.0           1.0  19.0  ...         0.0
Battle of the Fords            299.0           1.0  17.0  ...         0.0
Battle of the Golden Tooth     298.0           1.0   1.0  ...         1.0
Battle of the Green Fork       298.0           1.0   4.0  ...         1.0
Battle of the Ruby Ford        299.0           1.0  24.0  ...         0.0
Battle of the Stony Shore      299.0           1.0  10.0  ...         0.0
Battle of the Whispering Wood  298.0           1.0   5.0  ...         1.0
Fall of Moat Cailin            300.0           1.0  29.0  ...         0.0
Retaking of Harrenhal          299.0           1.0  25.0  ...         1.0
Sack of Darry                  298.0           1.0   7.0  ...         0.0
Sack of Harrenhal              299.0           1.0  18.0  ...         1.0
Sack of Torrhen's Square       299.0           1.0  13.0  ...         0.0
Sack of Winterfell             299.0           1.0  14.0  ...         1.0
Siege of Darry                 299.0           1.0  21.0  ...         0.0
Siege of Seagard               299.0           1.0  27.0  ...         0.0
Siege of Storm's End           299.0           1.0  16.0  ...         1.0
The Red Wedding                299.0           1.0  26.0  ...         1.0

                                   major_capture                               \
                               max         count mean std  min  25%  50%  75%
name
Battle at the Mummer's Ford    1.0           1.0  0.0 NaN  0.0  0.0  0.0  0.0
Battle of Castle Black         1.0           1.0  1.0 NaN  1.0  1.0  1.0  1.0
Battle of Deepwood Motte       0.0           1.0  0.0 NaN  0.0  0.0  0.0  0.0
Battle of Duskendale           1.0           1.0  0.0 NaN  0.0  0.0  0.0  0.0
Battle of Moat Cailin          0.0           1.0  0.0 NaN  0.0  0.0  0.0  0.0
Battle of Oxcross              1.0           1.0  1.0 NaN  1.0  1.0  1.0  1.0
Battle of Riverrun             0.0           1.0  1.0 NaN  1.0  1.0  1.0  1.0
Battle of Torrhen's Square     0.0           1.0  0.0 NaN  0.0  0.0  0.0  0.0
Battle of Winterfell           0.0           1.0  1.0 NaN  1.0  1.0  1.0  1.0
Battle of the Blackwater       1.0           1.0  1.0 NaN  1.0  1.0  1.0  1.0
Battle of the Burning Septry   0.0           1.0  0.0 NaN  0.0  0.0  0.0  0.0
Battle of the Camps            0.0           1.0  0.0 NaN  0.0  0.0  0.0  0.0
Battle of the Crag             0.0           1.0  0.0 NaN  0.0  0.0  0.0  0.0
Battle of the Fords            0.0           1.0  0.0 NaN  0.0  0.0  0.0  0.0
Battle of the Golden Tooth     1.0           1.0  0.0 NaN  0.0  0.0  0.0  0.0
Battle of the Green Fork       1.0           1.0  1.0 NaN  1.0  1.0  1.0  1.0
Battle of the Ruby Ford        0.0           1.0  0.0 NaN  0.0  0.0  0.0  0.0
Battle of the Stony Shore      0.0           1.0  0.0 NaN  0.0  0.0  0.0  0.0
Battle of the Whispering Wood  1.0           1.0  1.0 NaN  1.0  1.0  1.0  1.0
Fall of Moat Cailin            0.0           1.0  0.0 NaN  0.0  0.0  0.0  0.0
Retaking of Harrenhal          1.0           1.0  0.0 NaN  0.0  0.0  0.0  0.0
Sack of Darry                  0.0           1.0  0.0 NaN  0.0  0.0  0.0  0.0
Sack of Harrenhal              1.0           1.0  0.0 NaN  0.0  0.0  0.0  0.0
Sack of Torrhen's Square       0.0           1.0  1.0 NaN  1.0  1.0  1.0  1.0
Sack of Winterfell             1.0           1.0  0.0 NaN  0.0  0.0  0.0  0.0
Siege of Darry                 0.0           1.0  0.0 NaN  0.0  0.0  0.0  0.0
Siege of Seagard               0.0           1.0  1.0 NaN  1.0  1.0  1.0  1.0
Siege of Storm's End           1.0           1.0  0.0 NaN  0.0  0.0  0.0  0.0
The Red Wedding                1.0           1.0  1.0 NaN  1.0  1.0  1.0  1.0


                               max
name
Battle at the Mummer's Ford    0.0
Battle of Castle Black         1.0
Battle of Deepwood Motte       0.0
Battle of Duskendale           0.0
Battle of Moat Cailin          0.0
Battle of Oxcross              1.0
Battle of Riverrun             1.0
Battle of Torrhen's Square     0.0
Battle of Winterfell           1.0
Battle of the Blackwater       1.0
Battle of the Burning Septry   0.0
Battle of the Camps            0.0
Battle of the Crag             0.0
Battle of the Fords            0.0
Battle of the Golden Tooth     0.0
Battle of the Green Fork       1.0
Battle of the Ruby Ford        0.0
Battle of the Stony Shore      0.0
Battle of the Whispering Wood  1.0
Fall of Moat Cailin            0.0
Retaking of Harrenhal          0.0
Sack of Darry                  0.0
Sack of Harrenhal              0.0
Sack of Torrhen's Square       1.0
Sack of Winterfell             0.0
Siege of Darry                 0.0
Siege of Seagard               1.0
Siege of Storm's End           0.0
The Red Wedding                1.0

[29 rows x 32 columns]

In [18]:
df1 = pd.DataFrame({
    'city':['surat','navsari','bardoli'],
    'weather':['sunny','rain','snow']
})
df1

      city weather
0    surat   sunny
1  navsari    rain
2  bardoli    snow

In [19]:
df2 = pd.DataFrame({
    'city':['surat','vapi','bardoli'],
    'windspeed':['9','13','18']
})
df2

      city windspeed
0    surat         9
1     vapi        13
2  bardoli        18

In [23]:
df = pd.merge(df1,df2,on='city',how='outer',indicator=True)
df

      city weather windspeed      _merge
0    surat   sunny         9        both
1  navsari    rain       NaN   left_only
2  bardoli    snow        18        both
3     vapi     NaN        13  right_only

In [26]:
df3 = pd.merge(df1,df2,on='city',suffixes=('_left','_right'))
df3

      city weather windspeed
0    surat   sunny         9
1  bardoli    snow        18